import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ReduxProvider from "./redux/ReduxProvider";
import { getUserById, getUserCookie } from "./api/getuser";
import { get } from "http";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserById(getUserCookie());
  console.log(user, "Nasuser");

  return (
    <html lang="en">
      <body className={`${inter.className} h-full select-none`}>
        <ReduxProvider user={user} >
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
