import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ReduxProvider from "./redux/ReduxProvider";
import { getLocked, getUserById, getUserCookie } from "./api/getuser";
import { get } from "http";
import { getPlayers, getTrainers } from "./api/getPlayers";
import setUserPoints from "./api/getUserPoints/getUserPoints";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vbg Fantasy - Basket",
  description: "Generated by Aleksa Tesic, najveci car na planeti zemajlji",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserById(getUserCookie());
  const players = await getPlayers()
  const trainers = await getTrainers()
  if (user) console.log(await setUserPoints(1))
  const locked = await getLocked() || false
  return (
    <html lang="en">
      <body className={`${inter.className} h-full select-none`}>
        <ReduxProvider trainers={trainers} locked={locked} players={players} user={user} >
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
